# Generated by Django 4.0.4 on 2022-06-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='updated',
        ),
    ]
