# Generated by Django 4.0.4 on 2022-06-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_technology_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedWord',
            fields=[
                ('word', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Word')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'blacklisted word',
                'verbose_name_plural': 'blacklisted words',
                'ordering': ['word'],
            },
        ),
    ]
