# Generated by Django 4.0.4 on 2022-06-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='Position name')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('from_date', models.DateField(verbose_name='From date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-from_date'],
            },
        ),
    ]
